# Which files are YARA rules
files:
  accept:
  - "**.yar"
  - "**.yara"

# Negative datasets → anything matching here is a FALSE POSITIVE
false_positives:

false_negatives:
  disabled: true




