# Which files are YARA rules
files:
  accept:
  - "**.yar"
  - "**.yara"

# Negative datasets → anything matching here is a FALSE POSITIVE
false_positives:
  - query: 'entity:file type:peexe positives:0 fs:2024-01-01+ size:<100MB'
    limit: 30000
  - query: 'entity:file (type:pdf OR type:docx OR type:xlsx) positives:0 fs:2024-01-01+'
    limit: 20000
    
false_negatives:
  - query: 'entity:file tag:formbook p:10+ fs:2024-06-01+'   # replace with families you care about
    limit: 5000
  - query: 'entity:file tag:emotet  p:10+ fs:2024-06-01+'
    limit: 5000
