branches:
  accept:
    - "main"
    - "refs/pull/*"

files:
  accept:
    - "rules/*.yar"
    - "rules/*.yara"
  ignore:
    - "rules/_experimental/**"   # opsiyonel: gürültülü/hunt kuralları

# Kurallarında external variable kullanıyorsan burada tanımla (opsiyonel)
# variables:
#   my_external_variable: 10
# ↑ Dış değişkenleri burada tanımlamazsan derleme hatası alırsın.
# (Ayrıntı: "Defining variables") 
# 
false_negatives:
  # Kural metadatasından hangi alanlardan hash toplanacağını belirt
  meta_names:
    - "hash*"
    - "sha256*"
    - "sha1*"
    - "md5*"
false_positives:
  # Gürültülü kuralları kapsam dışı bırakma örnekleri (istenirse)
  ignore:
    - file: "rules/_experimental/**"
    - rule: "**generic**"
    - meta_value: "**hunt**"   # metadata'da "hunt" geçenleri sayma



